// Code generated by client-gen; DO NOT EDIT.

package wdk

type WalletStorageWriterClient struct {
	client *rpcWalletStorageWriter
}

func (c *WalletStorageWriterClient) Migrate(storageName string, storageIdentityKey string) (string, error) {
	return c.client.Migrate(storageName, storageIdentityKey)
}

func (c *WalletStorageWriterClient) MakeAvailable() (*TableSettings, error) {
	return c.client.MakeAvailable()
}

func (c *WalletStorageWriterClient) FindOrInsertUser(identityKey string) (*FindOrInsertUserResponse, error) {
	return c.client.FindOrInsertUser(identityKey)
}

func (c *WalletStorageWriterClient) CreateAction(auth AuthID, args ValidCreateActionArgs) (*StorageCreateActionResult, error) {
	return c.client.CreateAction(auth, args)
}

type rpcWalletStorageWriter struct {
	Migrate func(string, string) (string, error)

	MakeAvailable func() (*TableSettings, error)

	FindOrInsertUser func(string) (*FindOrInsertUserResponse, error)

	CreateAction func(AuthID, ValidCreateActionArgs) (*StorageCreateActionResult, error)
}
