// Code generated by client-gen; DO NOT EDIT.

package wdk

import (
	"context"
)

type WalletStorageWriterClient struct {
	client *rpcWalletStorageWriter
}

func (c *WalletStorageWriterClient) Migrate(ctx context.Context, storageName string, storageIdentityKey string) (string, error) {
	return c.client.Migrate(ctx, storageName, storageIdentityKey)
}

func (c *WalletStorageWriterClient) MakeAvailable(ctx context.Context) (*TableSettings, error) {
	return c.client.MakeAvailable(ctx)
}

func (c *WalletStorageWriterClient) FindOrInsertUser(ctx context.Context, identityKey string) (*FindOrInsertUserResponse, error) {
	return c.client.FindOrInsertUser(ctx, identityKey)
}

func (c *WalletStorageWriterClient) CreateAction(ctx context.Context, auth AuthID, args ValidCreateActionArgs) (*StorageCreateActionResult, error) {
	return c.client.CreateAction(ctx, auth, args)
}

func (c *WalletStorageWriterClient) InsertCertificateAuth(ctx context.Context, auth AuthID, certificate *TableCertificateX) (uint, error) {
	return c.client.InsertCertificateAuth(ctx, auth, certificate)
}

func (c *WalletStorageWriterClient) RelinquishCertificate(ctx context.Context, auth AuthID, args RelinquishCertificateArgs) error {
	return c.client.RelinquishCertificate(ctx, auth, args)
}

func (c *WalletStorageWriterClient) ListCertificates(ctx context.Context, auth AuthID, args ListCertificatesArgs) (*ListCertificatesResult, error) {
	return c.client.ListCertificates(ctx, auth, args)
}

type rpcWalletStorageWriter struct {
	Migrate               func(context.Context, string, string) (string, error)
	MakeAvailable         func(context.Context) (*TableSettings, error)
	FindOrInsertUser      func(context.Context, string) (*FindOrInsertUserResponse, error)
	CreateAction          func(context.Context, AuthID, ValidCreateActionArgs) (*StorageCreateActionResult, error)
	InsertCertificateAuth func(context.Context, AuthID, *TableCertificateX) (uint, error)
	RelinquishCertificate func(context.Context, AuthID, RelinquishCertificateArgs) error
	ListCertificates      func(context.Context, AuthID, ListCertificatesArgs) (*ListCertificatesResult, error)
}
