bsv_network: main
db:
    engine: sqlite
    max_connection_idle_time: 6m0s
    max_connection_time: 1m0s
    max_idle_connections: 5
    max_open_connections: 5
    mysql:
        db_name: storage
        host: localhost
        password: ""
        port: "3306"
        protocol: tcp
        time_zone: UTC
        user: root
    postgresql:
        db_name: storage
        host: localhost
        password: postgres
        port: "5432"
        ssl_mode: disable
        time_zone: UTC
        user: postgres
    sqlite:
        connection_string: ./storage.sqlite
http:
    port: 8100
logging:
    enabled: true
    handler: json
    level: info
name: go-storage-server
server_private_key: ""
