// Code generated by client-gen; DO NOT EDIT.

package storage

import (
	"context"
)

import "github.com/4chain-ag/go-wallet-toolbox/pkg/wdk"

type WalletStorageWriterClient struct {
	client *rpcWalletStorageWriter
}

func (c *WalletStorageWriterClient) Migrate(ctx context.Context, storageName string, storageIdentityKey string) (string, error) {
	return c.client.Migrate(ctx, storageName, storageIdentityKey)
}

func (c *WalletStorageWriterClient) MakeAvailable(ctx context.Context) (*wdk.TableSettings, error) {
	return c.client.MakeAvailable(ctx)
}

func (c *WalletStorageWriterClient) FindOrInsertUser(ctx context.Context, identityKey string) (*wdk.FindOrInsertUserResponse, error) {
	return c.client.FindOrInsertUser(ctx, identityKey)
}

func (c *WalletStorageWriterClient) CreateAction(ctx context.Context, auth wdk.AuthID, args wdk.ValidCreateActionArgs) (*wdk.StorageCreateActionResult, error) {
	return c.client.CreateAction(ctx, auth, args)
}

func (c *WalletStorageWriterClient) InsertCertificateAuth(ctx context.Context, auth wdk.AuthID, certificate *wdk.TableCertificateX) (uint, error) {
	return c.client.InsertCertificateAuth(ctx, auth, certificate)
}

func (c *WalletStorageWriterClient) RelinquishCertificate(ctx context.Context, auth wdk.AuthID, args wdk.RelinquishCertificateArgs) error {
	return c.client.RelinquishCertificate(ctx, auth, args)
}

func (c *WalletStorageWriterClient) ListCertificates(ctx context.Context, auth wdk.AuthID, args wdk.ListCertificatesArgs) (*wdk.ListCertificatesResult, error) {
	return c.client.ListCertificates(ctx, auth, args)
}

type rpcWalletStorageWriter struct {
	Migrate               func(context.Context, string, string) (string, error)
	MakeAvailable         func(context.Context) (*wdk.TableSettings, error)
	FindOrInsertUser      func(context.Context, string) (*wdk.FindOrInsertUserResponse, error)
	CreateAction          func(context.Context, wdk.AuthID, wdk.ValidCreateActionArgs) (*wdk.StorageCreateActionResult, error)
	InsertCertificateAuth func(context.Context, wdk.AuthID, *wdk.TableCertificateX) (uint, error)
	RelinquishCertificate func(context.Context, wdk.AuthID, wdk.RelinquishCertificateArgs) error
	ListCertificates      func(context.Context, wdk.AuthID, wdk.ListCertificatesArgs) (*wdk.ListCertificatesResult, error)
}
